BEGIN;
-- AUTO-GENERATED: DO NOT EDIT BY HAND
-- Generated by: dart run tool/generate_schema_comments.dart
-- Source: lib/src/**.spy.yaml (YAML comments: ### / #)


-- serverpod_auth_core_user 表注释
COMMENT ON TABLE "serverpod_auth_core_user" IS '认证用户主体表，存储用户的认证身份信息';
COMMENT ON COLUMN "serverpod_auth_core_user"."id" IS '用户唯一标识符（UUID v7）';
COMMENT ON COLUMN "serverpod_auth_core_user"."scopeNames" IS '用户被授予的权限范围列表，用于 API 端点访问控制（如 admin）';
COMMENT ON COLUMN "serverpod_auth_core_user"."blocked" IS '是否被封禁，true 表示该用户无法登录';
COMMENT ON COLUMN "serverpod_auth_core_user"."createdAt" IS '用户创建时间（UTC）';

-- serverpod_auth_core_profile 表注释
COMMENT ON TABLE "serverpod_auth_core_profile" IS '用户个人资料表，存储用户的基本信息（姓名、用户名、邮箱等）';

-- serverpod_auth_core_profile_image 表注释
COMMENT ON TABLE "serverpod_auth_core_profile_image" IS '用户头像图片表，存储用户的头像/个人资料图片数据';

-- serverpod_auth_core_session 表注释
COMMENT ON TABLE "serverpod_auth_core_session" IS '登录会话表，存储数据库支持的用户会话信息，用于验证用户登录状态';

-- serverpod_auth_core_jwt_refresh_token 表注释
COMMENT ON TABLE "serverpod_auth_core_jwt_refresh_token" IS 'JWT 刷新令牌表，存储 JWT 会话对应的 refresh token，令牌轮换时旧记录会被新记录替换';

-- =============================================
-- serverpod_auth_core_jwt_refresh_token
-- =============================================
COMMENT ON TABLE "serverpod_auth_core_jwt_refresh_token" IS 'JWT 刷新令牌表，存储 JWT 会话对应的 refresh token，令牌轮换时旧记录会被新记录替换';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."id" IS '刷新令牌唯一标识符（UUID v7）';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."authUserId" IS '关联的认证用户 ID，外键引用 serverpod_auth_core_user.id，用户删除时级联删除';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."scopeNames" IS '该令牌对应的权限范围列表（JSON 格式）';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."extraClaims" IS '附加的自定义 JWT Claims 数据（可为空）';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."method" IS '生成该令牌所使用的登录方式（如 email、google 等）';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."fixedSecret" IS '固定密钥（二进制），用于令牌验证';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."rotatingSecretHash" IS '轮换密钥的哈希值，令牌轮换时更新';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."lastUpdatedAt" IS '令牌最后更新时间（UTC）';
COMMENT ON COLUMN "serverpod_auth_core_jwt_refresh_token"."createdAt" IS '令牌创建时间（UTC）';

-- =============================================
-- serverpod_auth_core_profile
-- =============================================
COMMENT ON TABLE "serverpod_auth_core_profile" IS '用户个人资料表，存储用户的基本信息（用户名、全名、邮箱等）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."id" IS '个人资料唯一标识符（UUID v7）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."authUserId" IS '关联的认证用户 ID，外键引用 serverpod_auth_core_user.id，用户删除时级联删除，且每个用户只有一条资料记录（唯一索引）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."userName" IS '用户名（可为空）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."fullName" IS '用户全名（可为空）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."email" IS '用户邮箱地址（可为空）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."createdAt" IS '资料创建时间（UTC）';
COMMENT ON COLUMN "serverpod_auth_core_profile"."imageId" IS '关联的头像图片 ID，外键引用 serverpod_auth_core_profile_image.id（可为空）';

-- =============================================
-- serverpod_auth_core_profile_image
-- =============================================
COMMENT ON TABLE "serverpod_auth_core_profile_image" IS '用户头像图片表，存储用户头像的存储路径和访问地址';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."id" IS '头像图片唯一标识符（UUID v7）';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."userProfileId" IS '关联的用户资料 ID，外键引用 serverpod_auth_core_profile.id，资料删除时级联删除';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."createdAt" IS '图片上传时间（UTC）';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."storageId" IS '存储服务的存储桶/存储空间标识符';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."path" IS '图片在存储服务中的路径';
COMMENT ON COLUMN "serverpod_auth_core_profile_image"."url" IS '图片的公开访问 URL';

-- =============================================
-- serverpod_auth_core_session
-- =============================================
COMMENT ON TABLE "serverpod_auth_core_session" IS '登录会话表，存储数据库支持的用户会话信息，用于验证用户登录状态';
COMMENT ON COLUMN "serverpod_auth_core_session"."id" IS '会话唯一标识符（UUID v7）';
COMMENT ON COLUMN "serverpod_auth_core_session"."authUserId" IS '关联的认证用户 ID，外键引用 serverpod_auth_core_user.id，用户删除时级联删除';
COMMENT ON COLUMN "serverpod_auth_core_session"."scopeNames" IS '该会话对应的权限范围列表（JSON 格式）';
COMMENT ON COLUMN "serverpod_auth_core_session"."createdAt" IS '会话创建时间（UTC）';
COMMENT ON COLUMN "serverpod_auth_core_session"."lastUsedAt" IS '会话最后使用时间（UTC）';
COMMENT ON COLUMN "serverpod_auth_core_session"."expiresAt" IS '会话固定过期时间（UTC），为空表示不设固定过期';
COMMENT ON COLUMN "serverpod_auth_core_session"."expireAfterUnusedFor" IS '会话闲置超时时长（单位：秒），超过此时长未使用则过期，为空表示不限制';
COMMENT ON COLUMN "serverpod_auth_core_session"."sessionKeyHash" IS '会话密钥的哈希值（二进制），用于验证会话合法性';
COMMENT ON COLUMN "serverpod_auth_core_session"."sessionKeySalt" IS '会话密钥的盐值（二进制），用于哈希计算';
COMMENT ON COLUMN "serverpod_auth_core_session"."method" IS '生成该会话所使用的登录方式（如 email、google 等）';





COMMENT ON TABLE "book" IS '书籍基本信息表，用于存储书籍的基本信息';
COMMENT ON COLUMN "book"."author" IS '书籍的作者姓名';
COMMENT ON COLUMN "book"."categoryId" IS '书籍分类的ID，用于关联分类表';
COMMENT ON COLUMN "book"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "book"."image" IS '书籍封面的图片URL地址';
COMMENT ON COLUMN "book"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "book"."isbn" IS '书籍的ISBN编号，用于唯一标识一本书（唯一约束）';
COMMENT ON COLUMN "book"."keyword" IS '关键字';
COMMENT ON COLUMN "book"."name" IS '书籍的标题/书名（必填，唯一约束）';
COMMENT ON COLUMN "book"."originalPrice" IS '书籍的原价/定价（必填）';
COMMENT ON COLUMN "book"."publisher" IS '出版社名称';
COMMENT ON COLUMN "book"."updateTime" IS '记录最后更新时间';

COMMENT ON TABLE "book_category" IS '用于存储图书的分类信息';
COMMENT ON COLUMN "book_category"."createTime" IS '类别记录创建时间';
COMMENT ON COLUMN "book_category"."description" IS '类别的描述信息（可选）';
COMMENT ON COLUMN "book_category"."isDeleted" IS '是否删除';
COMMENT ON COLUMN "book_category"."name" IS '类别的名称（必填）';
COMMENT ON COLUMN "book_category"."updateTime" IS '类别记录最后更新时间';

COMMENT ON TABLE "book_inventory_log" IS '用于记录每本书库存变动的详细信息，便于审计和管理';
COMMENT ON COLUMN "book_inventory_log"."bookId" IS '图书ID，用于标识是哪本书';
COMMENT ON COLUMN "book_inventory_log"."changeTime" IS '变动发生的时间';
COMMENT ON COLUMN "book_inventory_log"."changeType" IS '变动类型，0=进货，1=售出，2=退货，3=损耗，4=库存调整';
COMMENT ON COLUMN "book_inventory_log"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "book_inventory_log"."description" IS '变动的原因或描述，提供额外的说明';
COMMENT ON COLUMN "book_inventory_log"."isDeleted" IS '是否删除';
COMMENT ON COLUMN "book_inventory_log"."quantity" IS '变动数量，可以为正（增加库存）或负（减少库存）';
COMMENT ON COLUMN "book_inventory_log"."updateTime" IS '记录最后更新时间';

COMMENT ON TABLE "book_package" IS '用于存储书籍组合套装的基本信息。';
COMMENT ON COLUMN "book_package"."contentDescription" IS '套装的描述内容';
COMMENT ON COLUMN "book_package"."createTime" IS '套装记录创建时间';
COMMENT ON COLUMN "book_package"."discountRate" IS '折扣率（例：0.8 表示八折）';
COMMENT ON COLUMN "book_package"."endTime" IS '失效时间';
COMMENT ON COLUMN "book_package"."isDeleted" IS '是否删除';
COMMENT ON COLUMN "book_package"."name" IS '套装名称（必填）';
COMMENT ON COLUMN "book_package"."originalPrice" IS '套装的原价（各书原价总和）';
COMMENT ON COLUMN "book_package"."salePrice" IS '套装的组合价格（实际售价）';
COMMENT ON COLUMN "book_package"."startTime" IS '生效时间';
COMMENT ON COLUMN "book_package"."status" IS '套装状态：0-下架，1-上架，2-预售';
COMMENT ON COLUMN "book_package"."updateTime" IS '套装记录最后更新时间';

COMMENT ON TABLE "book_package_item" IS '用于存储每个书籍套装中包含的书籍信息';
COMMENT ON COLUMN "book_package_item"."bookId" IS '关联的书籍ID';
COMMENT ON COLUMN "book_package_item"."createTime" IS '套餐明细记录创建时间';
COMMENT ON COLUMN "book_package_item"."discountRate" IS '单品折扣率';
COMMENT ON COLUMN "book_package_item"."isDeleted" IS '是否删除';
COMMENT ON COLUMN "book_package_item"."originalPrice" IS '此书籍的原价（冗余存储，便于历史查询）';
COMMENT ON COLUMN "book_package_item"."packageId" IS '关联的套餐ID';
COMMENT ON COLUMN "book_package_item"."packagePrice" IS '此书籍在套餐中的单价（可能与原价不同）';
COMMENT ON COLUMN "book_package_item"."quantity" IS '此书籍在套餐中的数量';
COMMENT ON COLUMN "book_package_item"."updateTime" IS '套餐明细记录最后更新时间';

COMMENT ON TABLE "book_sale" IS '用于存储书籍的销售记录信息';
COMMENT ON COLUMN "book_sale"."bookId" IS '图书的ID（如果是单本销售）';
COMMENT ON COLUMN "book_sale"."isDeleted" IS '是否删除';
COMMENT ON COLUMN "book_sale"."quantity" IS '出售数量';
COMMENT ON COLUMN "book_sale"."salePrice" IS '单本图书价格（单本出售）或套装总价（组合出售）';
COMMENT ON COLUMN "book_sale"."saleTime" IS '销售时间';

COMMENT ON TABLE "customer" IS '用于存储书店客户/会员的基本信息
customer: 面向前台的客户/会员账户系统';
COMMENT ON COLUMN "customer"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "customer"."email" IS '邮箱';
COMMENT ON COLUMN "customer"."memberLevel" IS '会员等级：0-普通会员，1-银卡会员，2-金卡会员';
COMMENT ON COLUMN "customer"."nickname" IS '昵称';
COMMENT ON COLUMN "customer"."password" IS '密码';
COMMENT ON COLUMN "customer"."phone" IS '手机号';
COMMENT ON COLUMN "customer"."status" IS '账户状态：0-正常，1-禁用';
COMMENT ON COLUMN "customer"."updateTime" IS '记录最后更新时间';
COMMENT ON COLUMN "customer"."userName" IS '用户名（唯一）';

COMMENT ON TABLE "infra_api_access_log" IS 'API 访问日志表';
COMMENT ON COLUMN "infra_api_access_log"."applicationName" IS '应用名';
COMMENT ON COLUMN "infra_api_access_log"."beginTime" IS '开始请求时间';
COMMENT ON COLUMN "infra_api_access_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_api_access_log"."creator" IS '创建者';
COMMENT ON COLUMN "infra_api_access_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_api_access_log"."duration" IS '执行时长';
COMMENT ON COLUMN "infra_api_access_log"."endTime" IS '结束请求时间';
COMMENT ON COLUMN "infra_api_access_log"."id" IS '日志主键，自增编号';
COMMENT ON COLUMN "infra_api_access_log"."operateModule" IS '操作模块';
COMMENT ON COLUMN "infra_api_access_log"."operateName" IS '操作名';
COMMENT ON COLUMN "infra_api_access_log"."operateType" IS '操作分类';
COMMENT ON COLUMN "infra_api_access_log"."requestMethod" IS '请求方法名';
COMMENT ON COLUMN "infra_api_access_log"."requestParams" IS '请求参数';
COMMENT ON COLUMN "infra_api_access_log"."requestUrl" IS '请求地址';
COMMENT ON COLUMN "infra_api_access_log"."responseBody" IS '响应结果';
COMMENT ON COLUMN "infra_api_access_log"."resultCode" IS '结果码';
COMMENT ON COLUMN "infra_api_access_log"."resultMsg" IS '结果提示';
COMMENT ON COLUMN "infra_api_access_log"."tenantId" IS '租户ID';
COMMENT ON COLUMN "infra_api_access_log"."traceId" IS '链路追踪编号';
COMMENT ON COLUMN "infra_api_access_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_api_access_log"."updater" IS '更新者';
COMMENT ON COLUMN "infra_api_access_log"."userAgent" IS '浏览器 UA';
COMMENT ON COLUMN "infra_api_access_log"."userId" IS '用户编号';
COMMENT ON COLUMN "infra_api_access_log"."userIp" IS '用户 IP';
COMMENT ON COLUMN "infra_api_access_log"."userType" IS '用户类型';

COMMENT ON TABLE "infra_api_error_log" IS '系统异常日志';
COMMENT ON COLUMN "infra_api_error_log"."applicationName" IS '应用名';
COMMENT ON COLUMN "infra_api_error_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_api_error_log"."creator" IS '创建者';
COMMENT ON COLUMN "infra_api_error_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_api_error_log"."exceptionClassName" IS '异常发生的类全名';
COMMENT ON COLUMN "infra_api_error_log"."exceptionFileName" IS '异常发生的类文件';
COMMENT ON COLUMN "infra_api_error_log"."exceptionLineNumber" IS '异常发生的方法所在行';
COMMENT ON COLUMN "infra_api_error_log"."exceptionMessage" IS '异常导致的消息';
COMMENT ON COLUMN "infra_api_error_log"."exceptionMethodName" IS '异常发生的方法名';
COMMENT ON COLUMN "infra_api_error_log"."exceptionName" IS '异常名';
COMMENT ON COLUMN "infra_api_error_log"."exceptionRootCauseMessage" IS '异常导致的根消息';
COMMENT ON COLUMN "infra_api_error_log"."exceptionStackTrace" IS '异常的栈轨迹';
COMMENT ON COLUMN "infra_api_error_log"."exceptionTime" IS '异常发生时间';
COMMENT ON COLUMN "infra_api_error_log"."id" IS '编号，主键';
COMMENT ON COLUMN "infra_api_error_log"."processStatus" IS '处理状态';
COMMENT ON COLUMN "infra_api_error_log"."processTime" IS '处理时间';
COMMENT ON COLUMN "infra_api_error_log"."processUserId" IS '处理用户编号';
COMMENT ON COLUMN "infra_api_error_log"."requestMethod" IS '请求方法名';
COMMENT ON COLUMN "infra_api_error_log"."requestParams" IS '请求参数';
COMMENT ON COLUMN "infra_api_error_log"."requestUrl" IS '请求地址';
COMMENT ON COLUMN "infra_api_error_log"."tenantId" IS '租户ID';
COMMENT ON COLUMN "infra_api_error_log"."traceId" IS '链路追踪编号';
COMMENT ON COLUMN "infra_api_error_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_api_error_log"."updater" IS '更新者';
COMMENT ON COLUMN "infra_api_error_log"."userAgent" IS '浏览器 UA';
COMMENT ON COLUMN "infra_api_error_log"."userId" IS '用户编号';
COMMENT ON COLUMN "infra_api_error_log"."userIp" IS '用户 IP';
COMMENT ON COLUMN "infra_api_error_log"."userType" IS '用户类型';

COMMENT ON TABLE "infra_file" IS '文件表';
COMMENT ON COLUMN "infra_file"."configId" IS '配置编号';
COMMENT ON COLUMN "infra_file"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_file"."creator" IS '创建者';
COMMENT ON COLUMN "infra_file"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_file"."id" IS '文件编号，主键';
COMMENT ON COLUMN "infra_file"."name" IS '文件名';
COMMENT ON COLUMN "infra_file"."path" IS '文件路径';
COMMENT ON COLUMN "infra_file"."size" IS '文件大小';
COMMENT ON COLUMN "infra_file"."type" IS '文件类型';
COMMENT ON COLUMN "infra_file"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_file"."updater" IS '更新者';
COMMENT ON COLUMN "infra_file"."url" IS '文件 URL';

COMMENT ON TABLE "infra_file_config" IS '文件配置表';
COMMENT ON COLUMN "infra_file_config"."config" IS '存储配置';
COMMENT ON COLUMN "infra_file_config"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_file_config"."creator" IS '创建者';
COMMENT ON COLUMN "infra_file_config"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_file_config"."id" IS '编号，主键';
COMMENT ON COLUMN "infra_file_config"."infra_file_config_name_unique" IS '文件配置名称全局唯一约束
确保系统中不能有重复的文件配置名称';
COMMENT ON COLUMN "infra_file_config"."master" IS '是否为主配置';
COMMENT ON COLUMN "infra_file_config"."name" IS '配置名';
COMMENT ON COLUMN "infra_file_config"."remark" IS '备注';
COMMENT ON COLUMN "infra_file_config"."storage" IS '存储器';
COMMENT ON COLUMN "infra_file_config"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_file_config"."updater" IS '更新者';

COMMENT ON TABLE "infra_file_content" IS '文件内容表';
COMMENT ON COLUMN "infra_file_content"."configId" IS '配置编号';
COMMENT ON COLUMN "infra_file_content"."content" IS '文件内容';
COMMENT ON COLUMN "infra_file_content"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_file_content"."creator" IS '创建者';
COMMENT ON COLUMN "infra_file_content"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_file_content"."id" IS '编号，主键';
COMMENT ON COLUMN "infra_file_content"."path" IS '文件路径';
COMMENT ON COLUMN "infra_file_content"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_file_content"."updater" IS '更新者';

COMMENT ON TABLE "infra_job" IS '定时任务表';
COMMENT ON COLUMN "infra_job"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_job"."creator" IS '创建者';
COMMENT ON COLUMN "infra_job"."cronExpression" IS 'CRON 表达式';
COMMENT ON COLUMN "infra_job"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_job"."handlerName" IS '处理器的名字';
COMMENT ON COLUMN "infra_job"."handlerParam" IS '处理器的参数';
COMMENT ON COLUMN "infra_job"."id" IS '任务编号，主键';
COMMENT ON COLUMN "infra_job"."monitorTimeout" IS '监控超时时间';
COMMENT ON COLUMN "infra_job"."name" IS '任务名称';
COMMENT ON COLUMN "infra_job"."retryCount" IS '重试次数';
COMMENT ON COLUMN "infra_job"."retryInterval" IS '重试间隔';
COMMENT ON COLUMN "infra_job"."status" IS '任务状态';
COMMENT ON COLUMN "infra_job"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_job"."updater" IS '更新者';

COMMENT ON TABLE "infra_job_log" IS '定时任务日志表';
COMMENT ON COLUMN "infra_job_log"."beginTime" IS '开始执行时间';
COMMENT ON COLUMN "infra_job_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "infra_job_log"."creator" IS '创建者';
COMMENT ON COLUMN "infra_job_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "infra_job_log"."duration" IS '执行时长';
COMMENT ON COLUMN "infra_job_log"."endTime" IS '结束执行时间';
COMMENT ON COLUMN "infra_job_log"."executeIndex" IS '第几次执行';
COMMENT ON COLUMN "infra_job_log"."handlerName" IS '处理器的名字';
COMMENT ON COLUMN "infra_job_log"."handlerParam" IS '处理器的参数';
COMMENT ON COLUMN "infra_job_log"."id" IS '日志编号，主键';
COMMENT ON COLUMN "infra_job_log"."jobId" IS '任务编号';
COMMENT ON COLUMN "infra_job_log"."result" IS '结果数据';
COMMENT ON COLUMN "infra_job_log"."status" IS '任务状态';
COMMENT ON COLUMN "infra_job_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "infra_job_log"."updater" IS '更新者';

COMMENT ON TABLE "region" IS '用于存储区域信息，如省市区等';
COMMENT ON COLUMN "region"."name" IS '名称（默认空字符串）';
COMMENT ON COLUMN "region"."parentId" IS '父级主键，无父级为 0';
COMMENT ON COLUMN "region"."pinyin" IS '拼音（默认空字符串）';

COMMENT ON TABLE "store" IS '店铺基本信息表，用于存储店铺的基本信息';
COMMENT ON COLUMN "store"."address" IS '店铺的地址';
COMMENT ON COLUMN "store"."contact" IS '店铺的联系方式';
COMMENT ON COLUMN "store"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "store"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "store"."logo" IS '店铺的logo';
COMMENT ON COLUMN "store"."name" IS '店铺的名称（必填）';
COMMENT ON COLUMN "store"."updateTime" IS '记录最后更新时间';

COMMENT ON COLUMN "store_activity"."address" IS '活动地点';
COMMENT ON COLUMN "store_activity"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "store_activity"."description" IS '活动描述';
COMMENT ON COLUMN "store_activity"."endTime" IS '结束时间';
COMMENT ON COLUMN "store_activity"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "store_activity"."name" IS '活动名称';
COMMENT ON COLUMN "store_activity"."startTime" IS '开始时间';
COMMENT ON COLUMN "store_activity"."storeId" IS '店铺ID';
COMMENT ON COLUMN "store_activity"."updateTime" IS '记录最后更新时间';

COMMENT ON COLUMN "store_activity_book"."activityId" IS '活动ID';
COMMENT ON COLUMN "store_activity_book"."bookId" IS '书籍ID';
COMMENT ON COLUMN "store_activity_book"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "store_activity_book"."discountPrice" IS '活动促销价';
COMMENT ON COLUMN "store_activity_book"."indexes" IS '使用唯一索引约束了 storeId, activityId 和 bookId 的组合。
这将确保了每个店铺，在每个活动中对每本书籍只能有一个记录。';
COMMENT ON COLUMN "store_activity_book"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "store_activity_book"."storeId" IS '店铺ID';
COMMENT ON COLUMN "store_activity_book"."updateTime" IS '记录最后更新时间';

COMMENT ON TABLE "store_book" IS '店铺图书关联表，用于存储店铺和图书的关联关系';
COMMENT ON COLUMN "store_book"."bookId" IS '图书ID';
COMMENT ON COLUMN "store_book"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "store_book"."discountPrice" IS '优惠价';
COMMENT ON COLUMN "store_book"."inventory" IS '库存';
COMMENT ON COLUMN "store_book"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "store_book"."purchasePrice" IS '进价';
COMMENT ON COLUMN "store_book"."salePrice" IS '售价';
COMMENT ON COLUMN "store_book"."storeId" IS '店铺ID';
COMMENT ON COLUMN "store_book"."updateTime" IS '记录最后更新时间';

COMMENT ON TABLE "store_sales_record" IS '店铺销售记录表，用于存储店铺的销售记录';
COMMENT ON COLUMN "store_sales_record"."activityId" IS '参与的活动ID（如果没有活动，`NULL`）';
COMMENT ON COLUMN "store_sales_record"."bookId" IS '书籍ID（如果是单本销售）';
COMMENT ON COLUMN "store_sales_record"."bookPackageId" IS '组合套餐的ID（如果是组合销售）';
COMMENT ON COLUMN "store_sales_record"."createTime" IS '记录创建时间';
COMMENT ON COLUMN "store_sales_record"."discountPrice" IS '优惠金额';
COMMENT ON COLUMN "store_sales_record"."isDeleted" IS '是否已删除（默认值：false）';
COMMENT ON COLUMN "store_sales_record"."paymentPrice" IS '# 实付金额';
COMMENT ON COLUMN "store_sales_record"."salePrice" IS '销售';
COMMENT ON COLUMN "store_sales_record"."saleTime" IS '销售时间';
COMMENT ON COLUMN "store_sales_record"."saleType" IS '销售类型：0-单本图书，1-组合套餐，2-赠品，3-促销等（可以根据需要扩展）';
COMMENT ON COLUMN "store_sales_record"."salesCount" IS '销售数量';
COMMENT ON COLUMN "store_sales_record"."storeId" IS '店铺ID（必填）';
COMMENT ON COLUMN "store_sales_record"."totalPrice" IS '单本图书价格（单本出售）或套装总价（组合出售）';
COMMENT ON COLUMN "store_sales_record"."updateTime" IS '记录最后更新时间';

COMMENT ON TABLE "sys_dept" IS '部门表';
COMMENT ON COLUMN "sys_dept"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_dept"."creator" IS '创建者';
COMMENT ON COLUMN "sys_dept"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_dept"."email" IS '邮箱';
COMMENT ON COLUMN "sys_dept"."id" IS '部门id，主键';
COMMENT ON COLUMN "sys_dept"."leaderUserId" IS '负责人';
COMMENT ON COLUMN "sys_dept"."name" IS '部门名称';
COMMENT ON COLUMN "sys_dept"."parentId" IS '父部门id';
COMMENT ON COLUMN "sys_dept"."phone" IS '联系电话';
COMMENT ON COLUMN "sys_dept"."sort" IS '显示顺序';
COMMENT ON COLUMN "sys_dept"."status" IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN "sys_dept"."sys_dept_name_parent_unique" IS '部门名称在父部门下唯一约束
确保同一个父部门下不能有重名的子部门';
COMMENT ON COLUMN "sys_dept"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_dept"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_dept"."updater" IS '更新者';

COMMENT ON TABLE "sys_dict_data" IS '字典数据表';
COMMENT ON COLUMN "sys_dict_data"."colorType" IS '颜色类型';
COMMENT ON COLUMN "sys_dict_data"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_dict_data"."creator" IS '创建者';
COMMENT ON COLUMN "sys_dict_data"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_dict_data"."dictType" IS '字典类型';
COMMENT ON COLUMN "sys_dict_data"."id" IS '字典编码，主键';
COMMENT ON COLUMN "sys_dict_data"."label" IS '字典标签';
COMMENT ON COLUMN "sys_dict_data"."remark" IS '备注';
COMMENT ON COLUMN "sys_dict_data"."sort" IS '字典排序';
COMMENT ON COLUMN "sys_dict_data"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sys_dict_data"."sys_dict_data_label_type_unique" IS '字典标签在字典类型下唯一约束
确保同一个字典类型下不能有重复的标签';
COMMENT ON COLUMN "sys_dict_data"."sys_dict_data_value_type_unique" IS '字典键值在字典类型下唯一约束
确保同一个字典类型下不能有重复的键值';
COMMENT ON COLUMN "sys_dict_data"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_dict_data"."updater" IS '更新者';
COMMENT ON COLUMN "sys_dict_data"."value" IS '字典键值';

COMMENT ON TABLE "sys_dict_type" IS '字典类型表';
COMMENT ON COLUMN "sys_dict_type"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_dict_type"."creator" IS '创建者';
COMMENT ON COLUMN "sys_dict_type"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_dict_type"."deletedTime" IS '删除时间';
COMMENT ON COLUMN "sys_dict_type"."id" IS '字典主键，自增编号';
COMMENT ON COLUMN "sys_dict_type"."name" IS '字典名称';
COMMENT ON COLUMN "sys_dict_type"."remark" IS '备注';
COMMENT ON COLUMN "sys_dict_type"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sys_dict_type"."sys_dict_type_unique" IS '字典类型编码全局唯一约束
确保系统中不能有重复的字典类型编码';
COMMENT ON COLUMN "sys_dict_type"."type" IS '字典类型';
COMMENT ON COLUMN "sys_dict_type"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_dict_type"."updater" IS '更新者';

COMMENT ON TABLE "sys_login_log" IS '系统访问记录';
COMMENT ON COLUMN "sys_login_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_login_log"."creator" IS '创建者';
COMMENT ON COLUMN "sys_login_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_login_log"."id" IS '访问ID，主键';
COMMENT ON COLUMN "sys_login_log"."logType" IS '日志类型';
COMMENT ON COLUMN "sys_login_log"."result" IS '登陆结果';
COMMENT ON COLUMN "sys_login_log"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_login_log"."traceId" IS '链路追踪编号';
COMMENT ON COLUMN "sys_login_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_login_log"."updater" IS '更新者';
COMMENT ON COLUMN "sys_login_log"."userAgent" IS '浏览器 UA';
COMMENT ON COLUMN "sys_login_log"."userId" IS '用户编号';
COMMENT ON COLUMN "sys_login_log"."userIp" IS '用户 IP';
COMMENT ON COLUMN "sys_login_log"."userType" IS '用户类型';
COMMENT ON COLUMN "sys_login_log"."username" IS '用户账号';

COMMENT ON TABLE "sys_mail_account" IS '邮箱账号表';
COMMENT ON COLUMN "sys_mail_account"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_mail_account"."creator" IS '创建者';
COMMENT ON COLUMN "sys_mail_account"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_mail_account"."host" IS 'SMTP 服务器域名';
COMMENT ON COLUMN "sys_mail_account"."id" IS '主键，自增编号';
COMMENT ON COLUMN "sys_mail_account"."mail" IS '邮箱';
COMMENT ON COLUMN "sys_mail_account"."password" IS '密码';
COMMENT ON COLUMN "sys_mail_account"."port" IS 'SMTP 服务器端口';
COMMENT ON COLUMN "sys_mail_account"."sslEnable" IS '是否开启 SSL';
COMMENT ON COLUMN "sys_mail_account"."starttlsEnable" IS '是否开启 STARTTLS';
COMMENT ON COLUMN "sys_mail_account"."sys_mail_account_mail_unique" IS '邮箱地址全局唯一约束
确保系统中不能有重复的邮箱地址';
COMMENT ON COLUMN "sys_mail_account"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_mail_account"."updater" IS '更新者';
COMMENT ON COLUMN "sys_mail_account"."username" IS '用户名';

COMMENT ON TABLE "sys_mail_log" IS '邮件日志表';
COMMENT ON COLUMN "sys_mail_log"."accountId" IS '邮箱账号编号';
COMMENT ON COLUMN "sys_mail_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_mail_log"."creator" IS '创建者';
COMMENT ON COLUMN "sys_mail_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_mail_log"."fromMail" IS '发送邮箱地址';
COMMENT ON COLUMN "sys_mail_log"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_mail_log"."sendException" IS '发送异常';
COMMENT ON COLUMN "sys_mail_log"."sendMessageId" IS '发送返回的消息 ID';
COMMENT ON COLUMN "sys_mail_log"."sendStatus" IS '发送状态';
COMMENT ON COLUMN "sys_mail_log"."sendTime" IS '发送时间';
COMMENT ON COLUMN "sys_mail_log"."templateCode" IS '模板编码';
COMMENT ON COLUMN "sys_mail_log"."templateContent" IS '邮件内容';
COMMENT ON COLUMN "sys_mail_log"."templateId" IS '模板编号';
COMMENT ON COLUMN "sys_mail_log"."templateNickname" IS '模版发送人名称';
COMMENT ON COLUMN "sys_mail_log"."templateParams" IS '邮件参数';
COMMENT ON COLUMN "sys_mail_log"."templateTitle" IS '邮件标题';
COMMENT ON COLUMN "sys_mail_log"."toMail" IS '接收邮箱地址';
COMMENT ON COLUMN "sys_mail_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_mail_log"."updater" IS '更新者';
COMMENT ON COLUMN "sys_mail_log"."userId" IS '用户编号';
COMMENT ON COLUMN "sys_mail_log"."userType" IS '用户类型';

COMMENT ON TABLE "sys_mail_template" IS '邮件模版表';
COMMENT ON COLUMN "sys_mail_template"."accountId" IS '发送的邮箱账号编号';
COMMENT ON COLUMN "sys_mail_template"."code" IS '模板编码';
COMMENT ON COLUMN "sys_mail_template"."content" IS '模板内容';
COMMENT ON COLUMN "sys_mail_template"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_mail_template"."creator" IS '创建者';
COMMENT ON COLUMN "sys_mail_template"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_mail_template"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_mail_template"."name" IS '模板名称';
COMMENT ON COLUMN "sys_mail_template"."nickname" IS '发送人名称';
COMMENT ON COLUMN "sys_mail_template"."params" IS '参数数组';
COMMENT ON COLUMN "sys_mail_template"."remark" IS '备注';
COMMENT ON COLUMN "sys_mail_template"."status" IS '开启状态';
COMMENT ON COLUMN "sys_mail_template"."sys_mail_template_code_unique" IS '邮件模板编码全局唯一约束
确保系统中不能有重复的邮件模板编码';
COMMENT ON COLUMN "sys_mail_template"."title" IS '模板标题';
COMMENT ON COLUMN "sys_mail_template"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_mail_template"."updater" IS '更新者';

COMMENT ON TABLE "sys_menu" IS '菜单权限表';
COMMENT ON COLUMN "sys_menu"."alwaysShow" IS '是否总是显示';
COMMENT ON COLUMN "sys_menu"."component" IS '组件路径';
COMMENT ON COLUMN "sys_menu"."componentName" IS '组件名';
COMMENT ON COLUMN "sys_menu"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_menu"."creator" IS '创建者';
COMMENT ON COLUMN "sys_menu"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_menu"."icon" IS '菜单图标';
COMMENT ON COLUMN "sys_menu"."id" IS '菜单ID，主键';
COMMENT ON COLUMN "sys_menu"."keepAlive" IS '是否缓存';
COMMENT ON COLUMN "sys_menu"."name" IS '菜单名称';
COMMENT ON COLUMN "sys_menu"."parentId" IS '父菜单ID';
COMMENT ON COLUMN "sys_menu"."path" IS '路由地址';
COMMENT ON COLUMN "sys_menu"."permission" IS '权限标识';
COMMENT ON COLUMN "sys_menu"."sort" IS '显示顺序';
COMMENT ON COLUMN "sys_menu"."status" IS '菜单状态';
COMMENT ON COLUMN "sys_menu"."sys_menu_name_parent_unique" IS '菜单名称在父菜单下唯一约束
确保同一个父菜单下不能有重名的子菜单';
COMMENT ON COLUMN "sys_menu"."sys_menu_permission_unique" IS '权限标识全局唯一约束
确保系统中不能有重复的权限标识';
COMMENT ON COLUMN "sys_menu"."type" IS '菜单类型';
COMMENT ON COLUMN "sys_menu"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_menu"."updater" IS '更新者';
COMMENT ON COLUMN "sys_menu"."visible" IS '是否可见';

COMMENT ON TABLE "sys_notice" IS '通知公告表';
COMMENT ON COLUMN "sys_notice"."content" IS '公告内容';
COMMENT ON COLUMN "sys_notice"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_notice"."creator" IS '创建者';
COMMENT ON COLUMN "sys_notice"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_notice"."id" IS '公告ID，主键';
COMMENT ON COLUMN "sys_notice"."status" IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN "sys_notice"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_notice"."title" IS '公告标题';
COMMENT ON COLUMN "sys_notice"."type" IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN "sys_notice"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_notice"."updater" IS '更新者';

COMMENT ON TABLE "sys_notify_message" IS '站内信消息表';
COMMENT ON COLUMN "sys_notify_message"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_notify_message"."creator" IS '创建者';
COMMENT ON COLUMN "sys_notify_message"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_notify_message"."id" IS '主键，自增编号';
COMMENT ON COLUMN "sys_notify_message"."readStatus" IS '是否已读';
COMMENT ON COLUMN "sys_notify_message"."readTime" IS '阅读时间';
COMMENT ON COLUMN "sys_notify_message"."templateCode" IS '模板编码';
COMMENT ON COLUMN "sys_notify_message"."templateContent" IS '模版内容';
COMMENT ON COLUMN "sys_notify_message"."templateId" IS '模版编号';
COMMENT ON COLUMN "sys_notify_message"."templateNickname" IS '模版发送人名称';
COMMENT ON COLUMN "sys_notify_message"."templateParams" IS '模版参数';
COMMENT ON COLUMN "sys_notify_message"."templateType" IS '模版类型';
COMMENT ON COLUMN "sys_notify_message"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_notify_message"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_notify_message"."updater" IS '更新者';
COMMENT ON COLUMN "sys_notify_message"."userId" IS '用户id';
COMMENT ON COLUMN "sys_notify_message"."userType" IS '用户类型';

COMMENT ON TABLE "sys_notify_template" IS '站内信模板表';
COMMENT ON COLUMN "sys_notify_template"."code" IS '模版编码';
COMMENT ON COLUMN "sys_notify_template"."content" IS '模版内容';
COMMENT ON COLUMN "sys_notify_template"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_notify_template"."creator" IS '创建者';
COMMENT ON COLUMN "sys_notify_template"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_notify_template"."id" IS '主键，自增编号';
COMMENT ON COLUMN "sys_notify_template"."name" IS '模板名称';
COMMENT ON COLUMN "sys_notify_template"."nickname" IS '发送人名称';
COMMENT ON COLUMN "sys_notify_template"."params" IS '参数数组';
COMMENT ON COLUMN "sys_notify_template"."remark" IS '备注';
COMMENT ON COLUMN "sys_notify_template"."status" IS '状态';
COMMENT ON COLUMN "sys_notify_template"."sys_notify_template_code_unique" IS '站内信模板编码全局唯一约束
确保系统中不能有重复的站内信模板编码';
COMMENT ON COLUMN "sys_notify_template"."type" IS '类型';
COMMENT ON COLUMN "sys_notify_template"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_notify_template"."updater" IS '更新者';

COMMENT ON TABLE "sys_operate_log" IS '操作日志记录 V2 版本';
COMMENT ON COLUMN "sys_operate_log"."action" IS '操作内容';
COMMENT ON COLUMN "sys_operate_log"."bizId" IS '操作数据模块编号';
COMMENT ON COLUMN "sys_operate_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_operate_log"."creator" IS '创建者';
COMMENT ON COLUMN "sys_operate_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_operate_log"."extra" IS '拓展字段';
COMMENT ON COLUMN "sys_operate_log"."id" IS '日志主键';
COMMENT ON COLUMN "sys_operate_log"."requestMethod" IS '请求方法名';
COMMENT ON COLUMN "sys_operate_log"."requestUrl" IS '请求地址';
COMMENT ON COLUMN "sys_operate_log"."subType" IS '操作名';
COMMENT ON COLUMN "sys_operate_log"."success" IS '操作结果';
COMMENT ON COLUMN "sys_operate_log"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_operate_log"."traceId" IS '链路追踪编号';
COMMENT ON COLUMN "sys_operate_log"."type" IS '操作模块类型';
COMMENT ON COLUMN "sys_operate_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_operate_log"."updater" IS '更新者';
COMMENT ON COLUMN "sys_operate_log"."userAgent" IS '浏览器 UA';
COMMENT ON COLUMN "sys_operate_log"."userId" IS '用户编号';
COMMENT ON COLUMN "sys_operate_log"."userIp" IS '用户 IP';
COMMENT ON COLUMN "sys_operate_log"."userType" IS '用户类型';

COMMENT ON TABLE "sys_post" IS '岗位信息表';
COMMENT ON COLUMN "sys_post"."code" IS '岗位编码';
COMMENT ON COLUMN "sys_post"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_post"."creator" IS '创建者';
COMMENT ON COLUMN "sys_post"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_post"."id" IS '岗位ID，主键';
COMMENT ON COLUMN "sys_post"."name" IS '岗位名称';
COMMENT ON COLUMN "sys_post"."remark" IS '备注';
COMMENT ON COLUMN "sys_post"."sort" IS '显示顺序';
COMMENT ON COLUMN "sys_post"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sys_post"."sys_post_code_tenant_unique" IS '岗位编码在租户内唯一约束
确保同一个租户下不能有重复的岗位编码';
COMMENT ON COLUMN "sys_post"."sys_post_name_tenant_unique" IS '岗位名称在租户内唯一约束
确保同一个租户下不能有重名的岗位';
COMMENT ON COLUMN "sys_post"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_post"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_post"."updater" IS '更新者';

COMMENT ON TABLE "sys_role" IS '角色信息表';
COMMENT ON COLUMN "sys_role"."code" IS '角色权限字符串';
COMMENT ON COLUMN "sys_role"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_role"."creator" IS '创建者';
COMMENT ON COLUMN "sys_role"."dataScope" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN "sys_role"."dataScopeDeptIds" IS '数据范围 (指定部门数组)';
COMMENT ON COLUMN "sys_role"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_role"."id" IS '角色ID，主键';
COMMENT ON COLUMN "sys_role"."name" IS '角色名称';
COMMENT ON COLUMN "sys_role"."remark" IS '备注';
COMMENT ON COLUMN "sys_role"."sort" IS '显示顺序';
COMMENT ON COLUMN "sys_role"."status" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "sys_role"."sys_role_code_tenant_unique" IS '角色编码在租户内唯一约束
确保同一个租户下不能有重复的角色编码';
COMMENT ON COLUMN "sys_role"."sys_role_name_tenant_unique" IS '角色名称在租户内唯一约束
确保同一个租户下不能有重名的角色';
COMMENT ON COLUMN "sys_role"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_role"."type" IS '角色类型';
COMMENT ON COLUMN "sys_role"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_role"."updater" IS '更新者';

COMMENT ON TABLE "sys_role_menu" IS '角色和菜单关联表';
COMMENT ON COLUMN "sys_role_menu"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_role_menu"."creator" IS '创建者';
COMMENT ON COLUMN "sys_role_menu"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_role_menu"."id" IS '主键，自增编号';
COMMENT ON COLUMN "sys_role_menu"."menuId" IS '菜单ID';
COMMENT ON COLUMN "sys_role_menu"."roleId" IS '角色ID';
COMMENT ON COLUMN "sys_role_menu"."sys_role_menu_unique" IS '角色-菜单关联唯一约束
确保同一个角色不能重复分配同一个菜单权限';
COMMENT ON COLUMN "sys_role_menu"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_role_menu"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_role_menu"."updater" IS '更新者';

COMMENT ON TABLE "sys_sms_channel" IS '短信渠道';
COMMENT ON COLUMN "sys_sms_channel"."apiKey" IS '短信 API 的账号';
COMMENT ON COLUMN "sys_sms_channel"."apiSecret" IS '短信 API 的秘钥';
COMMENT ON COLUMN "sys_sms_channel"."callbackUrl" IS '短信发送回调 URL';
COMMENT ON COLUMN "sys_sms_channel"."code" IS '渠道编码';
COMMENT ON COLUMN "sys_sms_channel"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_sms_channel"."creator" IS '创建者';
COMMENT ON COLUMN "sys_sms_channel"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_sms_channel"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_sms_channel"."remark" IS '备注';
COMMENT ON COLUMN "sys_sms_channel"."signature" IS '短信签名';
COMMENT ON COLUMN "sys_sms_channel"."status" IS '开启状态';
COMMENT ON COLUMN "sys_sms_channel"."sys_sms_channel_code_unique" IS '短信渠道编码全局唯一约束
确保系统中不能有重复的短信渠道编码';
COMMENT ON COLUMN "sys_sms_channel"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_sms_channel"."updater" IS '更新者';

COMMENT ON TABLE "sys_sms_code" IS '手机验证码';
COMMENT ON COLUMN "sys_sms_code"."code" IS '验证码';
COMMENT ON COLUMN "sys_sms_code"."createIp" IS '创建 IP';
COMMENT ON COLUMN "sys_sms_code"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_sms_code"."creator" IS '创建者';
COMMENT ON COLUMN "sys_sms_code"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_sms_code"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_sms_code"."mobile" IS '手机号';
COMMENT ON COLUMN "sys_sms_code"."scene" IS '发送场景';
COMMENT ON COLUMN "sys_sms_code"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_sms_code"."todayIndex" IS '今日发送的第几条';
COMMENT ON COLUMN "sys_sms_code"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_sms_code"."updater" IS '更新者';
COMMENT ON COLUMN "sys_sms_code"."used" IS '是否使用';
COMMENT ON COLUMN "sys_sms_code"."usedIp" IS '使用 IP';
COMMENT ON COLUMN "sys_sms_code"."usedTime" IS '使用时间';

COMMENT ON TABLE "sys_sms_log" IS '短信日志';
COMMENT ON COLUMN "sys_sms_log"."apiReceiveCode" IS 'API 接收结果的编码';
COMMENT ON COLUMN "sys_sms_log"."apiReceiveMsg" IS 'API 接收结果的说明';
COMMENT ON COLUMN "sys_sms_log"."apiRequestId" IS '短信 API 发送返回的唯一请求 ID';
COMMENT ON COLUMN "sys_sms_log"."apiSendCode" IS '短信 API 发送结果的编码';
COMMENT ON COLUMN "sys_sms_log"."apiSendMsg" IS '短信 API 发送失败的提示';
COMMENT ON COLUMN "sys_sms_log"."apiSerialNo" IS '短信 API 发送返回的序号';
COMMENT ON COLUMN "sys_sms_log"."apiTemplateId" IS '短信 API 的模板编号';
COMMENT ON COLUMN "sys_sms_log"."channelCode" IS '短信渠道编码';
COMMENT ON COLUMN "sys_sms_log"."channelId" IS '短信渠道编号';
COMMENT ON COLUMN "sys_sms_log"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_sms_log"."creator" IS '创建者';
COMMENT ON COLUMN "sys_sms_log"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_sms_log"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_sms_log"."mobile" IS '手机号';
COMMENT ON COLUMN "sys_sms_log"."receiveStatus" IS '接收状态';
COMMENT ON COLUMN "sys_sms_log"."receiveTime" IS '接收时间';
COMMENT ON COLUMN "sys_sms_log"."sendStatus" IS '发送状态';
COMMENT ON COLUMN "sys_sms_log"."sendTime" IS '发送时间';
COMMENT ON COLUMN "sys_sms_log"."templateCode" IS '模板编码';
COMMENT ON COLUMN "sys_sms_log"."templateContent" IS '短信内容';
COMMENT ON COLUMN "sys_sms_log"."templateId" IS '模板编号';
COMMENT ON COLUMN "sys_sms_log"."templateParams" IS '短信参数';
COMMENT ON COLUMN "sys_sms_log"."templateType" IS '短信类型';
COMMENT ON COLUMN "sys_sms_log"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_sms_log"."updater" IS '更新者';
COMMENT ON COLUMN "sys_sms_log"."userId" IS '用户编号';
COMMENT ON COLUMN "sys_sms_log"."userType" IS '用户类型';

COMMENT ON TABLE "sys_sms_template" IS '短信模板';
COMMENT ON COLUMN "sys_sms_template"."apiTemplateId" IS '短信 API 的模板编号';
COMMENT ON COLUMN "sys_sms_template"."channelCode" IS '短信渠道编码';
COMMENT ON COLUMN "sys_sms_template"."channelId" IS '短信渠道编号';
COMMENT ON COLUMN "sys_sms_template"."code" IS '模板编码';
COMMENT ON COLUMN "sys_sms_template"."content" IS '模板内容';
COMMENT ON COLUMN "sys_sms_template"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_sms_template"."creator" IS '创建者';
COMMENT ON COLUMN "sys_sms_template"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_sms_template"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_sms_template"."name" IS '模板名称';
COMMENT ON COLUMN "sys_sms_template"."params" IS '参数数组';
COMMENT ON COLUMN "sys_sms_template"."remark" IS '备注';
COMMENT ON COLUMN "sys_sms_template"."status" IS '开启状态';
COMMENT ON COLUMN "sys_sms_template"."sys_sms_template_code_unique" IS '短信模板编码全局唯一约束
确保系统中不能有重复的短信模板编码';
COMMENT ON COLUMN "sys_sms_template"."type" IS '模板类型';
COMMENT ON COLUMN "sys_sms_template"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_sms_template"."updater" IS '更新者';

COMMENT ON TABLE "sys_social_client" IS '社交客户端表';
COMMENT ON COLUMN "sys_social_client"."agentId" IS '代理编号';
COMMENT ON COLUMN "sys_social_client"."clientId" IS '客户端编号';
COMMENT ON COLUMN "sys_social_client"."clientSecret" IS '客户端密钥';
COMMENT ON COLUMN "sys_social_client"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_social_client"."creator" IS '创建者';
COMMENT ON COLUMN "sys_social_client"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_social_client"."id" IS '编号，主键';
COMMENT ON COLUMN "sys_social_client"."name" IS '应用名';
COMMENT ON COLUMN "sys_social_client"."socialType" IS '社交平台的类型';
COMMENT ON COLUMN "sys_social_client"."status" IS '状态';
COMMENT ON COLUMN "sys_social_client"."sys_social_client_code_unique" IS '社交客户端编号全局唯一约束
确保系统中不能有重复的客户端编号';
COMMENT ON COLUMN "sys_social_client"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_social_client"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_social_client"."updater" IS '更新者';
COMMENT ON COLUMN "sys_social_client"."userType" IS '用户类型';

COMMENT ON TABLE "sys_social_user" IS '社交用户表';
COMMENT ON COLUMN "sys_social_user"."avatar" IS '用户头像';
COMMENT ON COLUMN "sys_social_user"."code" IS '最后一次的认证 code';
COMMENT ON COLUMN "sys_social_user"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_social_user"."creator" IS '创建者';
COMMENT ON COLUMN "sys_social_user"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_social_user"."id" IS '主键，自增策略';
COMMENT ON COLUMN "sys_social_user"."nickname" IS '用户昵称';
COMMENT ON COLUMN "sys_social_user"."openid" IS '社交 openid';
COMMENT ON COLUMN "sys_social_user"."rawTokenInfo" IS '原始 Token 数据，一般是 JSON 格式';
COMMENT ON COLUMN "sys_social_user"."rawUserInfo" IS '原始用户数据，一般是 JSON 格式';
COMMENT ON COLUMN "sys_social_user"."state" IS '最后一次的认证 state';
COMMENT ON COLUMN "sys_social_user"."sys_social_user_openid_unique" IS '社交平台 openid 全局唯一约束
确保同一个社交平台的 openid 不能重复';
COMMENT ON COLUMN "sys_social_user"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_social_user"."token" IS '社交 token';
COMMENT ON COLUMN "sys_social_user"."type" IS '社交平台的类型';
COMMENT ON COLUMN "sys_social_user"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_social_user"."updater" IS '更新者';

COMMENT ON TABLE "sys_social_user_bind" IS '社交绑定表';
COMMENT ON COLUMN "sys_social_user_bind"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_social_user_bind"."creator" IS '创建者';
COMMENT ON COLUMN "sys_social_user_bind"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_social_user_bind"."id" IS '主键，自增策略';
COMMENT ON COLUMN "sys_social_user_bind"."socialType" IS '社交平台的类型';
COMMENT ON COLUMN "sys_social_user_bind"."socialUserId" IS '社交用户的编号';
COMMENT ON COLUMN "sys_social_user_bind"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_social_user_bind"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_social_user_bind"."updater" IS '更新者';
COMMENT ON COLUMN "sys_social_user_bind"."userId" IS '用户编号';
COMMENT ON COLUMN "sys_social_user_bind"."userType" IS '用户类型';

COMMENT ON TABLE "sys_tenant" IS '租户表';
COMMENT ON COLUMN "sys_tenant"."accountCount" IS '账号数量';
COMMENT ON COLUMN "sys_tenant"."contactMobile" IS '联系手机';
COMMENT ON COLUMN "sys_tenant"."contactName" IS '联系人';
COMMENT ON COLUMN "sys_tenant"."contactUserId" IS '联系人的用户编号';
COMMENT ON COLUMN "sys_tenant"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_tenant"."creator" IS '创建者';
COMMENT ON COLUMN "sys_tenant"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_tenant"."expireTime" IS '过期时间';
COMMENT ON COLUMN "sys_tenant"."id" IS '租户ID，主键';
COMMENT ON COLUMN "sys_tenant"."name" IS '租户名';
COMMENT ON COLUMN "sys_tenant"."packageId" IS '租户套餐编号';
COMMENT ON COLUMN "sys_tenant"."status" IS '租户状态（0正常 1停用）';
COMMENT ON COLUMN "sys_tenant"."sys_tenant_name_unique" IS '租户名称全局唯一约束
确保系统中不能有重名的租户';
COMMENT ON COLUMN "sys_tenant"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_tenant"."updater" IS '更新者';
COMMENT ON COLUMN "sys_tenant"."websites" IS '绑定域名数组';

COMMENT ON TABLE "sys_tenant_package" IS '租户套餐表';
COMMENT ON COLUMN "sys_tenant_package"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_tenant_package"."creator" IS '创建者';
COMMENT ON COLUMN "sys_tenant_package"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_tenant_package"."id" IS '套餐编号，主键';
COMMENT ON COLUMN "sys_tenant_package"."menuIds" IS '关联的菜单编号';
COMMENT ON COLUMN "sys_tenant_package"."name" IS '套餐名';
COMMENT ON COLUMN "sys_tenant_package"."remark" IS '备注';
COMMENT ON COLUMN "sys_tenant_package"."status" IS '租户状态（0正常 1停用）';
COMMENT ON COLUMN "sys_tenant_package"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_tenant_package"."updater" IS '更新者';

COMMENT ON TABLE "sys_user" IS '用户信息表';
COMMENT ON COLUMN "sys_user"."avatar" IS '头像地址';
COMMENT ON COLUMN "sys_user"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_user"."creator" IS '创建者';
COMMENT ON COLUMN "sys_user"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_user"."deptId" IS '用户的部门ID，关联 sys_dept 表';
COMMENT ON COLUMN "sys_user"."email" IS '用户邮箱';
COMMENT ON COLUMN "sys_user"."gender" IS '用户性别（0=男，1=女，2=未知）';
COMMENT ON COLUMN "sys_user"."id" IS '用户ID，主键，自增';
COMMENT ON COLUMN "sys_user"."loginIp" IS '最后登录IP';
COMMENT ON COLUMN "sys_user"."loginTime" IS '最后登录时间';
COMMENT ON COLUMN "sys_user"."nickname" IS '用户昵称';
COMMENT ON COLUMN "sys_user"."password" IS '密码（加密存储）';
COMMENT ON COLUMN "sys_user"."phone" IS '手机号码';
COMMENT ON COLUMN "sys_user"."postIds" IS '用户的多个岗位';
COMMENT ON COLUMN "sys_user"."remark" IS '备注信息';
COMMENT ON COLUMN "sys_user"."status" IS '帐号状态（0=正常，1=停用）';
COMMENT ON COLUMN "sys_user"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_user"."token" IS '用户Token（!persist=非持久化字段，不在数据库中创建）';
COMMENT ON COLUMN "sys_user"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_user"."updater" IS '更新者';
COMMENT ON COLUMN "sys_user"."username" IS '用户账号，唯一登录名';

COMMENT ON TABLE "sys_user_post" IS '用户岗位表';
COMMENT ON COLUMN "sys_user_post"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_user_post"."creator" IS '创建者';
COMMENT ON COLUMN "sys_user_post"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_user_post"."id" IS '主键';
COMMENT ON COLUMN "sys_user_post"."postId" IS '岗位ID';
COMMENT ON COLUMN "sys_user_post"."sys_user_post_unique" IS '用户-岗位关联唯一约束
确保同一个用户不能重复分配同一个岗位';
COMMENT ON COLUMN "sys_user_post"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_user_post"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_user_post"."updater" IS '更新者';
COMMENT ON COLUMN "sys_user_post"."userId" IS '用户ID';

COMMENT ON TABLE "sys_user_role" IS '用户和角色关联表';
COMMENT ON COLUMN "sys_user_role"."createTime" IS '创建时间';
COMMENT ON COLUMN "sys_user_role"."creator" IS '创建者';
COMMENT ON COLUMN "sys_user_role"."deleted" IS '是否删除';
COMMENT ON COLUMN "sys_user_role"."id" IS '主键';
COMMENT ON COLUMN "sys_user_role"."roleId" IS '角色ID';
COMMENT ON COLUMN "sys_user_role"."tenantId" IS '租户ID';
COMMENT ON COLUMN "sys_user_role"."updateTime" IS '更新时间';
COMMENT ON COLUMN "sys_user_role"."updater" IS '更新者';
COMMENT ON COLUMN "sys_user_role"."userId" IS '用户ID';

COMMIT;
