name: book_store_admin
description: "Book Store Admin System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # 状态管理和路由
  get: ^4.7.2
  # 顶部弹窗
  top_snackbar_flutter: ^3.2.0
  # 本地存储
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  # UI 组件
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  data_table_2_extended: ^2.5.20
  # fluent_ui: ^4.9.2 # 使用Flutter 设计漂亮的原生 Windows 应用demo https://bdlukaa.github.io/fluent_ui/

  # 日期时间选择器
  flutter_datetime_picker_plus: ^2.1.0
  # 图表
  fl_chart: ^0.66.0
  # 数据
  intl: ^0.19.0

  # data_table_2:
  #   path: packages/data_table_2-2.5.18
  side_menu:
    path: packages/side_menu-2b4ff2379f636c96645f6d43a8ec9f7537ff3837

  # 客户端共享代码
  book_store_client:
    path: ../book_store_client
  # 服务端共享代码
  book_store_shared:
    path: ../book_store_shared

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  # - assets/images/background.svg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
