# 部署配置
deploy:
  # 部署超时时间（秒）
  timeout: 300
  # 健康检查重试间隔（秒）
  health_check_interval: 5
  # 保留的版本数量
  keep_versions: 3
  # 是否启用部署锁
  enable_lock: true
  # 部署锁超时时间（秒）
  lock_timeout: 600

# 通知配置
notification:
  # 是否启用通知
  enabled: true
  # 通知 URL
  url: ""
  # 通知模板
  templates:
    success: "{env} 环境 {version} 版本部署成功"
    failure: "{env} 环境 {version} 版本部署失败: {error}"

# 日志配置
logging:
  # 日志级别
  level: "INFO"
  # 日志文件
  file: "deploy.log"
  # 日志格式
  format: "[%(asctime)s] %(levelname)s: %(message)s"
  # 日志保留天数
  retention_days: 30

# Docker 配置
docker:
  # 镜像仓库
  registry: ""
  # 命名空间
  namespace: ""
  # 构建平台
  platform: "linux/amd64"
  # 构建缓存目录
  cache_dir: "~/.docker/cache" 