name: flutter_web_admin_workspace

packages:
  - flutter_web_client
  - flutter_web_server
  - flutter_web_shared
  - serverpod_crud

sdkPath: .fvm/flutter_sdk   # 如果你使用 FVM，可以指定路径
ide:
  intellij: true
  vscode: true

command:
  version:
    linkToCommits: false
    message: "chore(release): publish"
    includeScopes: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  get: melos exec -- "flutter pub get"
  build: melos exec --dir-exists=build -- "flutter build"
  analyze: melos exec -- "flutter analyze"
  format: melos exec -- "dart format ."
  clean:
    run: |
      echo "🔧 正在清理所有模块"
      melos exec -- "flutter clean && echo ✅ {package} 清理完成"