name: flutter_web_admin_workspace
description: Melos workspace for Flutter Web Admin project
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"  # 统一 SDK 版本范围

sdkPath: .fvm/flutter_sdk   # 如果你使用 FVM，可以指定路径

# 统一管理 Serverpod 版本号 - 只需在这里修改一次，所有模块同步
dependency_overrides:
  serverpod: 3.0.0-alpha.2
  serverpod_client: 3.0.0-alpha.2
  serverpod_serialization: 3.0.0-alpha.2
  serverpod_shared: 3.0.0-alpha.2
  serverpod_flutter: 3.0.0-alpha.2
  serverpod_test: 3.0.0-alpha.2

dev_dependencies:
  melos: ^6.2.0