import 'dart:convert';
import 'dart:io';

/// Generates PostgreSQL `COMMENT ON ...` statements from Serverpod `.spy.yaml`
/// model files.
///
/// Why: Serverpod doesn't currently propagate model/YAML comments into DB
/// column/table comments. This script keeps comments next to the model and
/// applies them post-migration.
///
/// Supported comment sources (priority):
/// 1) Inline field comment after `#` on the same line
/// 2) Nearest preceding `###` doc comment block directly above a field
/// 3) Table comment from a `###` doc comment block before `fields:`
///
/// Usage:
///   dart run tool/generate_schema_comments.dart
///   dart run tool/generate_schema_comments.dart --out tool/generated/schema_comments.sql
///   dart run tool/generate_schema_comments.dart --root lib/src
Future<void> main(List<String> args) async {
  final outPath = _argValue(args, '--out') ?? _argValue(args, '-o');
  final root = _argValue(args, '--root') ?? 'lib/src';

  final sql = await _generateCommentsSql(rootDir: root);

  if (outPath == null) {
    stdout.write(sql);
    return;
  }

  final outFile = File(outPath);
  await outFile.parent.create(recursive: true);
  await outFile.writeAsString(sql, encoding: utf8);
}

String? _argValue(List<String> args, String key) {
  final i = args.indexOf(key);
  if (i == -1) return null;
  if (i + 1 >= args.length) return null;
  return args[i + 1];
}

class _TableComments {
  _TableComments({required this.tableName});
  final String tableName;
  String? tableComment;
  final Map<String, String> columnComments = {};
}

Future<String> _generateCommentsSql({required String rootDir}) async {
  final root = Directory(rootDir);
  if (!await root.exists()) {
    return _wrapSql([
      '-- No comments generated: root directory not found: $rootDir',
    ]);
  }

  final tables = <String, _TableComments>{};

  await for (final entity in root.list(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.spy.yaml')) continue;

    final parsed = await _parseSpyYaml(entity);
    for (final t in parsed) {
      final existing = tables.putIfAbsent(
        t.tableName,
        () => _TableComments(tableName: t.tableName),
      );

      // Prefer first non-empty table comment encountered.
      existing.tableComment ??= t.tableComment;

      // Column comments: prefer inline/field-local comment over existing one.
      for (final entry in t.columnComments.entries) {
        existing.columnComments[entry.key] ??= entry.value;
      }
    }
  }

  final stmts = <String>[];
  stmts.add('-- AUTO-GENERATED: DO NOT EDIT BY HAND');
  stmts.add('-- Generated by: dart run tool/generate_schema_comments.dart');
  stmts.add('-- Source: lib/src/**.spy.yaml (YAML comments: ### / #)');
  stmts.add('');

  final tableNames = tables.keys.toList()..sort();
  for (final tableName in tableNames) {
    final t = tables[tableName]!;
    final tableComment = t.tableComment?.trim();
    if (tableComment != null && tableComment.isNotEmpty) {
      stmts.add(_commentOnTable(tableName, tableComment));
    }

    final colNames = t.columnComments.keys.toList()..sort();
    for (final colName in colNames) {
      final comment = t.columnComments[colName]!.trim();
      if (comment.isEmpty) continue;
      stmts.add(_commentOnColumn(tableName, colName, comment));
    }

    if ((tableComment != null && tableComment.isNotEmpty) ||
        t.columnComments.isNotEmpty) {
      stmts.add('');
    }
  }

  if (stmts.length <= 4) {
    stmts.add('-- No comments found in .spy.yaml files.');
  }

  return _wrapSql(stmts);
}

String _wrapSql(List<String> lines) {
  // COMMENT statements are idempotent; wrap in a transaction for cleanliness.
  final out = <String>[];
  out.add('BEGIN;');
  out.addAll(lines);
  out.add('COMMIT;');
  out.add('');
  return out.join('\n');
}

String _escapeSqlString(String s) => s.replaceAll("'", "''");

String _quoteIdent(String ident) => '"${ident.replaceAll('"', '""')}"';

String _commentOnTable(String table, String comment) {
  return 'COMMENT ON TABLE ${_quoteIdent(table)} IS \'${_escapeSqlString(comment)}\';';
}

String _commentOnColumn(String table, String column, String comment) {
  return 'COMMENT ON COLUMN ${_quoteIdent(table)}.${_quoteIdent(column)} IS \'${_escapeSqlString(comment)}\';';
}

Future<List<_TableComments>> _parseSpyYaml(File file) async {
  final lines = await file.readAsLines(encoding: utf8);

  String? tableName;
  bool inFields = false;
  bool beforeFields = true;

  // Doc comments block (### ...) captured and applied to the next field.
  final pendingDoc = <String>[];
  // Table doc comment block (### ...) captured before `fields:`.
  final tableDoc = <String>[];

  final columnComments = <String, String>{};

  for (final raw in lines) {
    final line = raw.trimRight();
    final trimmed = line.trimLeft();

    // table: xxx
    final tableMatch = RegExp(
      r'^\s*table:\s*([A-Za-z0-9_]+)\s*$',
    ).firstMatch(line);
    if (tableMatch != null) {
      tableName = tableMatch.group(1);
      continue;
    }

    if (RegExp(r'^\s*fields:\s*$').hasMatch(line)) {
      inFields = true;
      beforeFields = false;
      continue;
    }

    // Capture doc comments: ### ...
    final docMatch = RegExp(r'^\s*###\s*(.*)\s*$').firstMatch(line);
    if (docMatch != null) {
      final text = (docMatch.group(1) ?? '').trim();
      if (text.isNotEmpty) {
        if (beforeFields) {
          tableDoc.add(text);
        } else {
          pendingDoc.add(text);
        }
      }
      continue;
    }

    if (!inFields) continue;
    if (trimmed.isEmpty) continue;
    if (trimmed.startsWith('#')) continue;
    if (trimmed.startsWith('-')) continue;

    // Leaving `fields:` section: a new top-level key (e.g. `indexes:`) starts.
    // In Serverpod .spy.yaml, field entries are indented (typically 2 spaces).
    if (RegExp(r'^[A-Za-z_]').hasMatch(line)) {
      inFields = false;
      pendingDoc.clear();
      continue;
    }

    // Field definition lines inside fields:
    //   fooBar: String, default = '' # comment
    //   foo: int?                   # comment
    final fieldMatch = RegExp(
      r'^\s{2,}([A-Za-z_][A-Za-z0-9_]*)\s*:\s*.*?(?:#\s*(.*))?\s*$',
    ).firstMatch(line);
    if (fieldMatch == null) continue;

    final fieldName = fieldMatch.group(1);
    if (fieldName == null) continue;

    // Skip non-persisted fields (Serverpod: `!persist` means the field is NOT
    // stored in the database).
    if (RegExp(r'(^|[ ,])!persist([ ,]|$)').hasMatch(line)) {
      pendingDoc.clear();
      continue;
    }

    final inlineComment = (fieldMatch.group(2) ?? '').trim();

    String? chosen;
    if (inlineComment.isNotEmpty) {
      chosen = inlineComment;
    } else if (pendingDoc.isNotEmpty) {
      chosen = pendingDoc.join('\n').trim();
    }

    pendingDoc.clear();

    if (chosen == null || chosen.isEmpty) continue;
    columnComments[fieldName] = chosen;
  }

  if (tableName == null || tableName.isEmpty) return [];

  final table = _TableComments(tableName: tableName);
  final tableComment = tableDoc.isEmpty ? null : tableDoc.join('\n').trim();
  if (tableComment != null && tableComment.isNotEmpty) {
    table.tableComment = tableComment;
  }
  table.columnComments.addAll(columnComments);

  return [table];
}
