type: server

client_package_path: ../book_store_client
server_test_tools_path: test/integration/test_tools


extraClasses:
- package:book_store_shared/book_store_shared.dart:BaseResponse
- package:book_store_shared/book_store_shared.dart:CommonResponse
- package:book_store_shared/book_store_shared.dart:PageResponse



# 可用的实验功能：
# inheritance：
# all：启用所有可用的实验功能
experimental_features:
  inheritance: true # Enables class inheritance in model files
  # or
  all: true # Enables all experimental features