name: flutter_web_admin
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  book_store_client:
    path: ../book_store_client
  book_store_shared:
    path: ../book_store_shared

  web: ^1.1.1
  uuid: ^4.5.1
  crypto: ^3.0.6                                                                  # 加密
  logger: ^2.6.1                                                                  # 日志打印
  getx_go: ^1.0.3                                                                 # 状态路由管理
  trina_grid: ^2.1.0                                                              # 表格组件
  flutter_svg: ^2.2.1                                                             # SVG图标
  get_storage:                                                                    # 本地缓存 (本地修改版,支持 Wasm)
    path: packages/get_storage
  common_utils: ^2.1.0                                                            # 通用工具
  easy_refresh: ^3.4.0                                                            # 下拉刷新
  path_provider: ^2.1.5                                                           # 文件路径
  cupertino_icons: ^1.0.8                                                         # 图标
  device_info_plus: ^12.1.0                                                       # 设备信息
  flutter_highlight: ^0.7.0                                                       # 代码高亮
  animated_text_kit: ^4.2.3                                                       # 动画文本
  web_socket_channel: ^3.0.3                                                      # WebSocket
  url_launcher: ^6.3.1                                                            # URL 启动器
  permission_handler: ^12.0.1                                                     # 权限管理
  top_snackbar_flutter: ^3.2.0                                                    # 顶部弹窗
  cached_network_image: ^3.4.1                                                    # 图片缓存
  ffmpeg_kit_flutter_new: ^3.2.0                                                  # 音频处理
  flutter_smart_dialog: ^4.9.8+7                                                  # 弹窗
  # get: ^5.0.0-release-candidate-9.3.2                                             # 状态路由管理
  flutter_spinkit: ^5.2.2                                                         # 加载动画
  http_manager:                                                                   # 网络请求
    git:
        url: https://gitee.com/coderxslee/http_manager.git
  
  record: ^6.1.1                                                                  # 录音功能
  # geolocator: ^13.0.2                                                           # 定位功能
  # speech_to_text: ^7.0.1                                                        # 语音识别（录音、语音识别、实时转写，iOS 用 Siri，Android 用 Google Speech API）




dependency_overrides:
  record_linux: ^1.2.1                                                             # 录音 Linux 实现
  record_platform_interface: ^1.4.0                                                # 录音平台接口


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0                                                            # 代码规范
  flutter_launcher_icons: ^0.14.3                                                  # 添加应用图标生成工具依赖



flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/empty_data.png
    - assets/images/menu_home.svg
    - assets/images/menu_chart.svg
    - assets/images/menu_data.svg
    - assets/images/menu_detail.svg
    - assets/images/menu_document.svg
    - assets/images/menu_error.svg
    - assets/images/menu_example.svg
    - assets/images/menu_file.svg
    - assets/images/menu_form.svg
    - assets/images/menu_layout.svg
    - assets/images/menu_multi.svg
    - assets/images/menu_nav.svg
    - assets/images/menu_result.svg
    - assets/images/menu_system.svg
    - assets/images/menu_table.svg
    - assets/images/menu_test.svg
    - assets/images/menu_about.svg
    - assets/images/menu_gitee.svg
    - assets/images/icon_user.svg
    - assets/images/icon_msg.svg
    - assets/images/icon_notice.svg
    - assets/images/icon_num.svg
    - assets/images/icon_wait.svg
    - assets/images/file.svg
    - assets/images/file_open.svg
    - assets/images/file_close.svg
    - assets/images/file_css.svg
    - assets/images/file_dir.svg
    - assets/images/file_excel.svg
    - assets/images/file_exe.svg
    - assets/images/file_html.svg
    - assets/images/file_image.svg
    - assets/images/file_js.svg
    - assets/images/file_json.svg
    - assets/images/file_music.svg
    - assets/images/file_other.svg
    - assets/images/file_pdf.svg
    - assets/images/file_ppt.svg
    - assets/images/file_rar.svg
    - assets/images/file_txt.svg
    - assets/images/file_video.svg
    - assets/images/file_wps.svg
    - assets/images/file_zip.svg
    - assets/images/upload_file.svg
    - assets/images/upload_folder.svg
    - assets/images/avatar_man.svg
    - assets/images/avatar_woman.svg
    - assets/images/backtop.svg
    - assets/images/time.svg
    - assets/images/alipay.svg
    - assets/images/arco.svg
    - assets/images/wechat.svg
    - assets/images/vite.svg
    - assets/images/vue.svg
    - assets/images/item_angular.svg
    - assets/images/item_github.svg
    - assets/images/item_html5.svg
    - assets/images/item_js.svg
    - assets/images/item_react.svg
    - assets/images/item_vue.svg
    - assets/images/dart.png
    - assets/images/flutter.png
    - assets/images/serverpod.png
    - assets/images/postgresql.png
    - assets/images/flutter_illustration.png
    - assets/images/serverpod_illustration.webp
  
  # 字体通过 web/index.html 中的 @font-face 加载
  # 不在此处定义，避免重复打包到 assets
  # fonts:
  #   - family: NotoSansSC
  #     fonts:
  #       - asset: assets/fonts/NotoSansSC-Regular.ttf
  #         weight: 400
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700