type: server

client_package_path: ../flutter_web_client
server_test_tools_path: test/integration/test_tools


extraClasses:
- package:flutter_web_shared/shared.dart:BaseResponse
- package:flutter_web_shared/shared.dart:CommonResponse
- package:flutter_web_shared/shared.dart:PageResponse

# 模块的别名将决定客户端如何引用该模块。
# 可以选择性地添加 serverpod_auth_idp 模块并为其指定一个别名nickname。
# 如果模块未添加到 config/generator.yaml 则将使用该模块的默认别名。
modules:
  serverpod_auth_idp:
    nickname: authIdp
  serverpod_auth_core:
    nickname: authCore

# 可用的实验功能：
# inheritance：
# all：启用所有可用的实验功能
experimental_features:
  inheritance: true # Enables class inheritance in model files
  # or
  all: true # Enables all experimental features