name: book_store_shared
description: Shared models and utilities for book store project.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  json_annotation: ^4.8.1
  serverpod_serialization: ^2.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  