# 简化版 Docker Compose 配置
# 只包含必要的时区设置

version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: flutter_web_admin_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-flutter_web_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # 只需要这两行来设置时区
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    container_name: flutter_web_admin_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_web_admin_app
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      TZ: Asia/Shanghai
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB:-flutter_web_admin}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      runmode: production
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:




