services:
  # 服务器服务
  server:
    build: 
      context: ../../..
      dockerfile: book_store_server/Dockerfile
    image: book_store_server:1.0
    ports:
      - "8080:8080"
    env_file:
      - ../../env/.env.production
    environment:
      - runmode=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - ./config:/app/book_store_server/config
    networks:
      - book_store_network

  postgres:
    image: postgres:16.3
    ports:
      - '5432:5432'
    env_file:
      - ../../env/.env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - book_store_data:/var/lib/postgresql/data
    restart: always
    networks:
      - book_store_network

  # Redis 服务
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../../env/.env.production
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - book_store_network

  # Nginx 服务
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # 如果需要 HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl  # 如果需要 HTTPS
    depends_on:
      - server
    restart: always
    networks:
      - book_store_network

volumes:
  book_store_data:

networks:
  book_store_network:
    driver: bridge

    