version: '3.8'

  # **************************************************
  # 服务
  # **************************************************
services:
  # 服务器服务
  server:
    image: ${IMAGE_NAME}  # 使用我们上传的本地镜像
    ports:
      - "8080:8080"
    container_name: book_store_server
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - book_store_network
    env_file:
      - .env.production  # 改为相对于部署目录的路径
    depends_on:
      - postgres
      - redis
    # 添加 labels 方便在 Portainer 中识别
    labels:
      - "version=${VERSION}"
      - "com.docker.compose.project=${IMAGE_NAME}"
      - "com.docker.compose.service=app"
      - "maintainer=your-team"
      - "traefik.enable=true"
      - "traefik.http.routers.${IMAGE_NAME}.rule=Host(`${DOMAIN}`)"
      # Portainer 标签
      - "portainer.group=production"
      - "portainer.notes=生产环境应用"
      - "portainer.template.name=${IMAGE_NAME}"
      # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  # **************************************************
  # Postgres 服务
  # **************************************************
  postgres:
    image: postgres:16.3
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - book_store_data:/var/lib/postgresql/data
    env_file:
      - .env.production  # 这里会加载所有环境变量
    networks:
      - book_store_network




  # **************************************************
  # Redis 服务
  # **************************************************
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    env_file:
      - .env.production
    # 使用 entrypoint 覆盖默认命令
    entrypoint: >
      sh -c '
        redis-server --requirepass "$${REDIS_PASSWORD}"
      '
    networks:
      - book_store_network

  # Nginx 服务
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"  # 如果需要 HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl  # 如果需要 HTTPS
    depends_on:
      - server
    restart: always
    networks:
      - book_store_network

volumes:
  book_store_data:

networks:
  book_store_network:
    driver: bridge

    