name: book_store_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  serverpod_client: any
  book_store_shared:
    path: ../book_store_shared
    
