type: server

client_package_path: ../book_store_client
server_test_tools_path: test/integration/test_tools


extraClasses:
- package:book_store_shared/book_store_shared.dart:BaseResponse
- package:book_store_shared/book_store_shared.dart:CommonResponse
- package:book_store_shared/book_store_shared.dart:PageResponse



serializableModels:
  - BaseResponse
  - CommonResponse
  - PageResponse


serializable:
  enabled: true
  models:
    - BaseResponse
    - CommonResponse
    - PageResponse


classes:
  - name: CommonResponse
    modelPath: book_store_shared/lib/src/models/common_response.dart
  - name: BaseResponse
    modelPath: book_store_shared/lib/src/models/base_response.dart
  - name: PageResponse
    modelPath: book_store_shared/lib/src/models/page_response.dart
