name: flutter_web_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  serverpod_client: any
  flutter_web_shared:
    path: ../flutter_web_shared
    
