version: '3'
services:
  # mysql:
  #   image: mysql:8.0.33
  #   restart: always
  #   container_name: mysql
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     TZ: Asia/Shanghai
  #     MYSQL_ROOT_PASSWORD: as0qwerlaksdjfo2391023812093841c
  #     # 初始化数据库（后续的初始化 SQL 会在这个库执行）
  #     MYSQL_DATABASE: continew_admin
  #     #MYSQL_USER: 你的数据库用户名
  #     #MYSQL_PASSWORD: 你的数据库密码
  #   volumes:
  #     - ~/docker/mysql/conf/:/etc/mysql/conf.d/
  #     - ~/docker/mysql/data/:/var/lib/mysql/
  #   command:
  #     --default-authentication-plugin=mysql_native_password
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --explicit_defaults_for_timestamp=true
  #     --lower_case_table_names=1
  postgresql:
    image: postgres:16.3
    restart: always
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: coderxslee
      POSTGRES_PASSWORD: postgres_password_202503262210
      POSTGRES_DB: continew_admin
    volumes:
      - /docker/continew-admin/config/postgresql/data/:/var/lib/postgresql/data/
  redis:
    image: redis:7.2.3
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/continew/redis/conf/redis.conf:/usr/local/redis/config/redis.conf
      - /opt/continew/redis/data/:/data/
      - /opt/continew/redis/logs/:/logs/
    command: 'redis-server /usr/local/redis/config/redis.conf --appendonly yes --requirepass redis_password_202503262210'
  continew-admin-server:
    build: ./continew-admin
    restart: always
    container_name: continew-admin-server
    ports:
      - '18000:18000'
      - '1789:1789'
    environment:
      TZ: Asia/Shanghai
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      DB_USER: coderxslee
      DB_PWD: postgres_password_202503262210
      DB_NAME: continew
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379
      REDIS_PWD: redis_password_202503262210
      REDIS_DB: 0
      SCHEDULE_HOST: 172.17.0.1
      SCHEDULE_PORT: 1788
      SCHEDULE_TOKEN: 任务调度服务端 Token
    volumes:
      - /opt/continew/continew-admin/config/:/app/config/
      - /opt/continew/continew-admin/data/file/:/app/data/file/
      - /opt/continew/continew-admin/logs/:/app/logs/
      - /opt/continew/continew-admin/lib/:/app/lib/
    depends_on:
      - redis
      - postgresql
  # 定时任务调度服务
  schedule-server:
    build: ./schedule-server
    restart: always
    container_name: continew-admin-schedule-server
    ports:
      - '18001:18001'
      - '1788:1788'
    environment:
      TZ: Asia/Shanghai
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      DB_USER: coderxslee
      DB_PWD: postgres_password_202503262210
      DB_NAME: continew_admin
    volumes:
      - /opt/continew/schedule-server/logs/:/app/logs/
    depends_on:
      - postgresql
  nginx:
    image: nginx:1.25.3
    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/continew/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/continew/nginx/cert/:/etc/nginx/cert/
      - /opt/continew/nginx/logs/:/var/log/nginx/
      # 前端页面目录
      - /opt/continew/continew-admin/html/:/usr/share/nginx/html/
