name: getx_go_main
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  book_store_client:
    path: ../book_store_client
  book_store_shared:
    path: ../book_store_shared

  web: ^1.1.1
  uuid: ^4.5.1
  crypto: ^3.0.6                                                                  # 加密
  logger: ^2.6.1                                                                  # 日志打印
  getx_go: ^1.0.3                                                                 # 状态路由管理
  flutter_svg: ^2.2.1                                                             # SVG图标
  get_storage: ^2.1.1                                                             # 本地缓存
  common_utils: ^2.1.0                                                            # 通用工具
  easy_refresh: ^3.4.0                                                            # 下拉刷新
  path_provider: ^2.1.5                                                           # 文件路径
  cupertino_icons: ^1.0.8                                                         # 图标
  device_info_plus: ^12.1.0                                                       # 设备信息
  flutter_highlight: ^0.7.0                                                       # 代码高亮
  animated_text_kit: ^4.2.3                                                       # 动画文本
  web_socket_channel: ^3.0.3                                                      # WebSocket
  url_launcher: ^6.3.1                                                            # URL 启动器
  permission_handler: ^12.0.1                                                     # 权限管理
  top_snackbar_flutter: ^3.2.0                                                    # 顶部弹窗
  cached_network_image: ^3.4.1                                                    # 图片缓存
  ffmpeg_kit_flutter_new: ^3.2.0                                                  # 音频处理
  flutter_smart_dialog: ^4.9.8+7                                                  # 弹窗
  # get: ^5.0.0-release-candidate-9.3.2                                             # 状态路由管理
  flutter_spinkit: ^5.2.2                                                         # 加载动画
  http_manager:                                                                   # 网络请求
    git:
        url: https://gitee.com/coderxslee/http_manager.git
  
  record: ^6.1.1                                                                  # 录音功能
  # geolocator: ^13.0.2                                                           # 定位功能
  # speech_to_text: ^7.0.1                                                        # 语音识别（录音、语音识别、实时转写，iOS 用 Siri，Android 用 Google Speech API）




dependency_overrides:
  record_linux: ^1.2.1                                                             # 录音 Linux 实现
  record_platform_interface: ^1.4.0                                                # 录音平台接口


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0                                                            # 代码规范
  flutter_launcher_icons: ^0.14.3                                                  # 添加应用图标生成工具依赖



flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/images/empty_data.png
    - assets/icons/menu_home.svg
    - assets/icons/menu_chart.svg
    - assets/icons/menu_data.svg
    - assets/icons/menu_detail.svg
    - assets/icons/menu_document.svg
    - assets/icons/menu_error.svg
    - assets/icons/menu_example.svg
    - assets/icons/menu_file.svg
    - assets/icons/menu_form.svg
    - assets/icons/menu_layout.svg
    - assets/icons/menu_multi.svg
    - assets/icons/menu_nav.svg
    - assets/icons/menu_result.svg
    - assets/icons/menu_system.svg
    - assets/icons/menu_table.svg
    - assets/icons/menu_test.svg
    - assets/icons/menu_about.svg
    - assets/icons/icon_user.svg
    - assets/icons/icon_msg.svg
    - assets/icons/icon_notice.svg
    - assets/icons/icon_num.svg
    - assets/icons/icon_wait.svg
    - assets/icons/file.svg
    - assets/icons/file_open.svg
    - assets/icons/file_close.svg
    - assets/icons/upload_file.svg
    - assets/icons/upload_folder.svg
    - assets/icons/backtop.svg
    - assets/icons/time.svg
    
  
  fonts:
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700